version: '3.8'

services:
  meeting-room:
    image: tw/meetingroom
    container_name: meeting-room
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./database:/app/database
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
