version: '3.8'

services:
  meeting-room:
    image: ghcr.io/taowei20/meetingroom:latest
    container_name: meeting-room
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./database:/app/database
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
