# 服务器配置
server:
  host: "0.0.0.0"
  port: 5000
  debug: False
  SECRET_KEY: "uns-23498wernkasdfu2341234Kdjw8e"

# 数据库配置
database:
  path: "../database/meeting_room.db"

# 文件上传配置
upload:
  folder: "./uploads"
  allowed_extensions:
    - "pdf"
    - "doc"
    - "docx"
    - "xls"
    - "xlsx"
    - "ppt"
    - "pptx"
    - "txt"
    - "jpg"
    - "jpeg"
    - "png"
    - "gif"
    - "zip"
    - "rar"
    - "7z"
    - "gz"
    - "tar"
  max_content_length: 102428800  # 100MB

# JWT配置
jwt:
  access_token_expires: 86400  # 24小时（秒）
  JWT_SECRET_KEY: "uns-is498wernkasdfCd2341234Kd8xw"
